// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqOPRcTd-MpP8LRVuvTAQ4QHKqNDvq2QQ',
    appId: '1:584658171555:android:8e30435e51b84b1a9bf116',
    messagingSenderId: '584658171555',
    projectId: 'urclinic-72a3e',
    storageBucket: 'urclinic-72a3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJOVCOFAvHYfdBLfWyZAZNX6tzHHxqRmY',
    appId: '1:584658171555:ios:cca1795b82fe4b369bf116',
    messagingSenderId: '584658171555',
    projectId: 'urclinic-72a3e',
    storageBucket: 'urclinic-72a3e.firebasestorage.app',
    iosBundleId: 'com.urclinic.patient',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcL6cJMuKf8wyFtaB2PRGgFKj6GKEChjQ',
    appId: '1:584658171555:web:9ef9b9e7a342ab0d9bf116',
    messagingSenderId: '584658171555',
    projectId: 'urclinic-72a3e',
    authDomain: 'urclinic-72a3e.firebaseapp.com',
    storageBucket: 'urclinic-72a3e.firebasestorage.app',
  );

}